[platformio]
src_dir = .

[env:esp32dev]
platform      = espressif32
board         = esp32dev
framework     = arduino
monitor_speed = 115200
upload_speed  = 460800
board_build.filesystem = spiffs
build_src_filter =
    +<main.cpp>
lib_deps =
    ottowinter/ESPAsyncWebServer-esphome @ ^3.1.0
    esphome/AsyncTCP-esphome            @ ^2.1.0
build_flags   =
    -DCORE_DEBUG_LEVEL=0
